[package]
name = "managed-command"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.61"
simple-broadcaster = { git = "https://github.com/rajputrajat/simple-broadcaster" }
tracing = "0.1.40"

[dev-dependencies]
tracing-subscriber = "*"
anyhow = "*"
pretty_assertions = "1"
